### ISSUE TITLE
Port to Python3 and other fixes.

### ISSUE THREAD

**Issue by vesellov** [microserv/entangled-dht#1]
Hello.

I did a port of Entangled to Python3 and also made some other improvements and fixes.
Successfully using it in our project.

I decided to include the source code of Entangled directly into our repo and avoid PyPi dependency to keep all of the code in same place. 

Here you can find the code which was inherited from the original Entangled sources I found on sourceforge years ago: https://github.com/bitdust-io/public/tree/master/dht/entangled

Would you consider to incorporate my changes into your repo so other people can also benefit?

If so I can try to prepare a pull request - there will be a lot of changes! :)))

**Comment by ninist** [comment]
These repositories were part of a project in a course and I do not believe they are maintained.
Although I also do not know whether there exists a maintained (official or semi-official) version of entangled.

I should say that I am not very familiar with this particular repository, though.

**Comment by vesellov** [comment]
but who is the owner or posses permissions to merge, @ninist ?

my only intention was (when i saw that repo) to re-use already existing repo... 
I mean I can start a fork and publish my changes there, but if it is already exists - better to collaborate :)

**Comment by paalka** [comment]
Hey,
thanks for making these improvements!

As @ninist mentioned, this project is not being actively maintained, and I don't think anyone else is using it at the moment (at least based on GitHub traffic).

So, i think the best option might be to create a fork. If you create a fork, I'll add a note in the README so that people interested will be able to find your repo more easily :)
